import type { Product, ProductDept } from "@/context/TenantProductsContext";

export const LAVIVIANE_COMPANY_ID = "laviviane-trial";

export const LAVIVIANE_CATEGORY_ORDER = [
  "New Cake Collection",
  "Laviviane Cakes",
  "Celebration Bites",
  "Mousse Cake",
  "Laviviane Bites",
  "Sandwich",
  "Luxury Chocolate",
  "Occasion Chocolate",
  "Distributions and Gifts",
] as const;

export type LavivianeCategory = typeof LAVIVIANE_CATEGORY_ORDER[number];
export type LavivianeProductSeed = Omit<Product, "companyId" | "createdAt" | "updatedAt"> & {
  category: LavivianeCategory;
  sourceFile?: string;
  sourcePage?: number;
};

function normalizeProductKey(product: Pick<LavivianeProductSeed, "name" | "price" | "category">) {
  return `${product.category}|${product.name}`
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ") + `|${Number(product.price).toFixed(2)}`;
}

// ── Page 2: New Cake's Collection ─────────────────────────────────────────────

const PAGE2: LavivianeProductSeed[] = [
  {
    id: "lavi-001",
    name: "بيرامود رفاهية المولود الجديد - 87 حبة",
    nameEn: "Luxury Newborn Pyramid - 87 Pcs",
    price: 475,
    department: "cake" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/01_New_Cake_s_Collection_Page_2/01_01_p2.png",
    sourceFile: "01_New_Cake_s_Collection_Page_2/01_01_p2.png",
    sourcePage: 2,
    isAvailable: true,
    sortOrder: 1010,
  },
  {
    id: "lavi-002",
    name: "بوكس سلايدر تشيز",
    nameEn: "Slider Cheesecake Box",
    price: 170,
    department: "cake" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/01_New_Cake_s_Collection_Page_2/01_02_p2.png",
    sourceFile: "01_New_Cake_s_Collection_Page_2/01_02_p2.png",
    sourcePage: 2,
    isAvailable: true,
    sortOrder: 1020,
  },
  {
    id: "lavi-003",
    name: "برتسلز شوكليت على صينية بيضاوية",
    nameEn: "Mix Pretzels Chocolate on Ceramic Tray",
    price: 285,
    department: "chocolate" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/01_New_Cake_s_Collection_Page_2/01_03_p2.png",
    sourceFile: "01_New_Cake_s_Collection_Page_2/01_03_p2.png",
    sourcePage: 2,
    isAvailable: true,
    sortOrder: 1030,
  },
  {
    id: "lavi-004",
    name: "سخان الشوكليت الكرانشي",
    nameEn: "Chocolate Crunchy Heater",
    price: 325,
    department: "chocolate" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/01_New_Cake_s_Collection_Page_2/01_04_p2.png",
    sourceFile: "01_New_Cake_s_Collection_Page_2/01_04_p2.png",
    sourcePage: 2,
    isAvailable: true,
    sortOrder: 1040,
  },
  {
    id: "lavi-005",
    name: "سخان كريمل بالتمر",
    nameEn: "Date Caramel Heater",
    price: 315,
    department: "halwa" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/01_New_Cake_s_Collection_Page_2/01_05_p2.png",
    sourceFile: "01_New_Cake_s_Collection_Page_2/01_05_p2.png",
    sourcePage: 2,
    isAvailable: true,
    sortOrder: 1050,
  },
];

// ── Page 3: New Cake's Collection ─────────────────────────────────────────────

const PAGE3: LavivianeProductSeed[] = [
  {
    id: "lavi-006",
    name: "صينية شوكليت فاخرة",
    nameEn: "Mix Special Chocolate in Ceramic Tray",
    price: 370,
    department: "chocolate" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/02_New_Cake_s_Collection_Page_3/02_01_p3.png",
    sourceFile: "02_New_Cake_s_Collection_Page_3/02_01_p3.png",
    sourcePage: 3,
    isAvailable: true,
    sortOrder: 1060,
  },
  {
    id: "lavi-007",
    name: "كيكة الماجو كريم بورلية",
    nameEn: "Mango Cream Brulee Cake",
    price: 265,
    department: "cake" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/02_New_Cake_s_Collection_Page_3/02_02_p3.png",
    sourceFile: "02_New_Cake_s_Collection_Page_3/02_02_p3.png",
    sourcePage: 3,
    isAvailable: true,
    sortOrder: 1070,
  },
  {
    id: "lavi-008",
    name: "تشيز كيك الماجو - صغير",
    nameEn: "Mango Cheesecake - Small",
    price: 57,
    department: "cake" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/02_New_Cake_s_Collection_Page_3/02_03_p3.png",
    sourceFile: "02_New_Cake_s_Collection_Page_3/02_03_p3.png",
    sourcePage: 3,
    isAvailable: true,
    sortOrder: 1080,
  },
  {
    id: "lavi-009",
    name: "تشيز كيك التوت - صغير",
    nameEn: "Raspberry Cheesecake - Small",
    price: 58,
    department: "cake" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/02_New_Cake_s_Collection_Page_3/02_04_p3.png",
    sourceFile: "02_New_Cake_s_Collection_Page_3/02_04_p3.png",
    sourcePage: 3,
    isAvailable: true,
    sortOrder: 1090,
  },
  {
    id: "lavi-010",
    name: "بوكس مشگل حالي ومالح - كبير",
    nameEn: "Sweet & Salty Mixed Box - Large",
    price: 370,
    department: "mawali" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/02_New_Cake_s_Collection_Page_3/02_05_p3.png",
    sourceFile: "02_New_Cake_s_Collection_Page_3/02_05_p3.png",
    sourcePage: 3,
    isAvailable: true,
    sortOrder: 1100,
  },
  {
    id: "lavi-011",
    name: "بوكس مشگل حالي ومالح - صغير",
    nameEn: "Sweet & Salty Mixed Box - Small",
    price: 189,
    department: "mawali" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/02_New_Cake_s_Collection_Page_3/02_05_p3.png",
    sourceFile: "02_New_Cake_s_Collection_Page_3/02_05_p3.png",
    sourcePage: 3,
    isAvailable: true,
    sortOrder: 1110,
  },
  {
    id: "lavi-012",
    name: "بوكس أصابع مالح - كبير",
    nameEn: "Savory Sticks Box - Large",
    price: 265,
    department: "mawali" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/02_New_Cake_s_Collection_Page_3/02_06_p3.png",
    sourceFile: "02_New_Cake_s_Collection_Page_3/02_06_p3.png",
    sourcePage: 3,
    isAvailable: true,
    sortOrder: 1120,
  },
  {
    id: "lavi-013",
    name: "بوكس أصابع مالح - صغير",
    nameEn: "Savory Sticks Box - Small",
    price: 95,
    department: "mawali" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/02_New_Cake_s_Collection_Page_3/02_06_p3.png",
    sourceFile: "02_New_Cake_s_Collection_Page_3/02_06_p3.png",
    sourcePage: 3,
    isAvailable: true,
    sortOrder: 1130,
  },
  {
    id: "lavi-014",
    name: "بوكس أي - شوفان وسمسم",
    nameEn: "Mae Sesame Box",
    price: 95,
    department: "mawali" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/02_New_Cake_s_Collection_Page_3/02_07_p3.png",
    sourceFile: "02_New_Cake_s_Collection_Page_3/02_07_p3.png",
    sourcePage: 3,
    isAvailable: true,
    sortOrder: 1140,
  },
  {
    id: "lavi-015",
    name: "كيك العسل بايتس - 18 حبة",
    nameEn: "Honey Cake Box - 18 Pcs",
    price: 125,
    department: "cake" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/02_New_Cake_s_Collection_Page_3/02_07_p3.png",
    sourceFile: "02_New_Cake_s_Collection_Page_3/02_07_p3.png",
    sourcePage: 3,
    isAvailable: true,
    sortOrder: 1150,
  },
  {
    id: "lavi-016",
    name: "تارت التمر - 18 حبة",
    nameEn: "Date Tart - 18 Pcs",
    price: 79,
    department: "halwa" as ProductDept,
    category: "New Cake Collection",
    imageUri: "/laviviane-cards/02_New_Cake_s_Collection_Page_3/02_08_p3.png",
    sourceFile: "02_New_Cake_s_Collection_Page_3/02_08_p3.png",
    sourcePage: 3,
    isAvailable: true,
    sortOrder: 1160,
  },
];

// ── Page 4: Laviviane Cakes ────────────────────────────────────────────────────

const PAGE4: LavivianeProductSeed[] = [
  {
    id: "lavi-017",
    name: "كيكة الليمون - صغير",
    nameEn: "Lemon Cake - Small",
    price: 29,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "/laviviane-cards/03_Laviviane_Cake_s/03_01_p4.png",
    sourceFile: "03_Laviviane_Cake_s/03_01_p4.png",
    sourcePage: 4,
    isAvailable: true,
    sortOrder: 2010,
  },
  {
    id: "lavi-018",
    name: "كيكة ردفيلفت فولكينو - صغير",
    nameEn: "Red Velvet Cake - Small",
    price: 46,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "/laviviane-cards/03_Laviviane_Cake_s/03_02_p4.png",
    sourceFile: "03_Laviviane_Cake_s/03_02_p4.png",
    sourcePage: 4,
    isAvailable: true,
    sortOrder: 2020,
  },
  {
    id: "lavi-019",
    name: "نوتيلا كيك - صغير",
    nameEn: "Nutella Cake - Small",
    price: 39,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "/laviviane-cards/03_Laviviane_Cake_s/03_03_p4.png",
    sourceFile: "03_Laviviane_Cake_s/03_03_p4.png",
    sourcePage: 4,
    isAvailable: true,
    sortOrder: 2030,
  },
  {
    id: "lavi-020",
    name: "نوتيلا بيستاشيو كيك - صغير",
    nameEn: "Nutella Pistachio Cake - Small",
    price: 39,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "/laviviane-cards/03_Laviviane_Cake_s/03_04_p4.png",
    sourceFile: "03_Laviviane_Cake_s/03_04_p4.png",
    sourcePage: 4,
    isAvailable: true,
    sortOrder: 2040,
  },
  {
    id: "lavi-021",
    name: "سلايد بوكس كيك 4 أنواع - مع كتابه",
    nameEn: "Slider Cake Box with Writing - 4 Types",
    price: 173,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "/laviviane-cards/03_Laviviane_Cake_s/03_05_p4.png",
    sourceFile: "03_Laviviane_Cake_s/03_05_p4.png",
    sourcePage: 4,
    isAvailable: true,
    sortOrder: 2050,
  },
  {
    id: "lavi-022",
    name: "ميني إكلير كريم برولية مغطاه بالشوكولانة - كبير",
    nameEn: "Mini Eclair Cream Brulee Chocolate - Big",
    price: 140,
    department: "chocolate" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "/laviviane-cards/03_Laviviane_Cake_s/03_06_p4.png",
    sourceFile: "03_Laviviane_Cake_s/03_06_p4.png",
    sourcePage: 4,
    isAvailable: true,
    sortOrder: 2060,
  },
];

// ── Laviviane Cakes (Medium / Large / Specialty additions) ────────────────────

const LAVIVIANE_CAKES_EXTRA: LavivianeProductSeed[] = [
  {
    id: "lavi-023",
    name: "كيكة الليمون - وسط",
    nameEn: "Lemon Cake - Medium",
    price: 207,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2070,
  },
  {
    id: "lavi-024",
    name: "كيكة الليمون - كبير",
    nameEn: "Lemon Cake - Large",
    price: 299,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2080,
  },
  {
    id: "lavi-025",
    name: "كيكة ريد فيلفت - وسط",
    nameEn: "Red Velvet Cake - Medium",
    price: 253,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2090,
  },
  {
    id: "lavi-026",
    name: "كيكة ريد فيلفت - كبير",
    nameEn: "Red Velvet Cake - Large",
    price: 368,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2100,
  },
  {
    id: "lavi-027",
    name: "تشيز كيك ريد فيلفت",
    nameEn: "Red Velvet Cheesecake",
    price: 207,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2110,
  },
  {
    id: "lavi-028",
    name: "نوتيلا كيك - كبير",
    nameEn: "Nutella Cake - Large",
    price: 253,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2120,
  },
  {
    id: "lavi-029",
    name: "نوتيلا بيستاشيو كيك - كبير",
    nameEn: "Nutella Pistachio Cake - Large",
    price: 253,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2130,
  },
  {
    id: "lavi-030",
    name: "كيكة التيراميسو",
    nameEn: "Tiramisu Cake",
    price: 253,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2140,
  },
  {
    id: "lavi-031",
    name: "كيكة البيكان بالتمر",
    nameEn: "Pecan Date Cake",
    price: 230,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2150,
  },
  {
    id: "lavi-032",
    name: "كيكة فيينا",
    nameEn: "Vienna Cake",
    price: 220,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2160,
  },
  {
    id: "lavi-033",
    name: "سلايد بوكس كيك 4 أنواع - بدون كتابة",
    nameEn: "Slider Cake Box without Writing - 4 Types",
    price: 153,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2170,
  },
  {
    id: "lavi-034",
    name: "ميني إكلير كريم برولية كراميل - كبير",
    nameEn: "Mini Eclair Cream Brulee Caramel - Large",
    price: 140,
    department: "chocolate" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2180,
  },
  {
    id: "lavi-035",
    name: "ميني إكلير كريم برولية كراميل - صغير",
    nameEn: "Mini Eclair Cream Brulee Caramel - Small",
    price: 42,
    department: "chocolate" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2190,
  },
  {
    id: "lavi-036",
    name: "ميني إكلير كريم برولية شوكولاتة - صغير",
    nameEn: "Mini Eclair Cream Brulee Chocolate - Small",
    price: 42,
    department: "chocolate" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2200,
  },
  {
    id: "lavi-037",
    name: "كيك موس الشوكولاتة - 4 أشخاص",
    nameEn: "Chocolate Mousse Cake - 4 Person",
    price: 155,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2210,
  },
  {
    id: "lavi-038",
    name: "كيك موس الشوكولاتة - كبير",
    nameEn: "Chocolate Mousse Cake - Large",
    price: 207,
    department: "cake" as ProductDept,
    category: "Laviviane Cakes",
    imageUri: "",
    isAvailable: true,
    sortOrder: 2220,
  },
];

// ── Celebration Bites ──────────────────────────────────────────────────────────

const CELEBRATION_BITES: LavivianeProductSeed[] = [
  {
    id: "lavi-039",
    name: "بايتس عقيلي للاحتفالات - 24 حبة",
    nameEn: "Celebration Oqaili Bites - 24 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Celebration Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 3010,
  },
  {
    id: "lavi-040",
    name: "بايتس الليمون للاحتفالات - 24 حبة",
    nameEn: "Celebration Lemon Bites - 24 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Celebration Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 3020,
  },
  {
    id: "lavi-041",
    name: "بايتس الفستق للاحتفالات",
    nameEn: "Celebration Pistachio Bites",
    price: 145,
    department: "cake" as ProductDept,
    category: "Celebration Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 3030,
  },
  {
    id: "lavi-042",
    name: "بايتس التيراميسو للاحتفالات - 24 حبة",
    nameEn: "Celebration Tiramisu Bites - 24 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Celebration Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 3040,
  },
  {
    id: "lavi-043",
    name: "بايتس البيكان بالتمر للاحتفالات",
    nameEn: "Celebration Pecan Date Bites",
    price: 145,
    department: "cake" as ProductDept,
    category: "Celebration Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 3050,
  },
  {
    id: "lavi-044",
    name: "صينية بايتس مشكل للاحتفالات",
    nameEn: "Celebration Mix Bites Tray",
    price: 145,
    department: "cake" as ProductDept,
    category: "Celebration Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 3060,
  },
  {
    id: "lavi-045",
    name: "بايتس التشيز للاحتفالات - 24 حبة",
    nameEn: "Celebration Cheese Bites - 24 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Celebration Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 3070,
  },
  {
    id: "lavi-046",
    name: "بايتس موس الشوكولاتة للاحتفالات - 24 حبة",
    nameEn: "Celebration Chocolate Mousse Bites - 24 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Celebration Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 3080,
  },
];

// ── Mousse Cake ────────────────────────────────────────────────────────────────

const MOUSSE_CAKE: LavivianeProductSeed[] = [
  {
    id: "lavi-047",
    name: "موس كيك النوتيلا - صغير",
    nameEn: "Nutella Cake Mousse - Small",
    price: 35,
    department: "cake" as ProductDept,
    category: "Mousse Cake",
    imageUri: "",
    isAvailable: true,
    sortOrder: 4010,
  },
  {
    id: "lavi-048",
    name: "موس كيك الفستق - صغير",
    nameEn: "Pistachio Cake Mousse - Small",
    price: 35,
    department: "cake" as ProductDept,
    category: "Mousse Cake",
    imageUri: "",
    isAvailable: true,
    sortOrder: 4020,
  },
  {
    id: "lavi-049",
    name: "موس كيك البيكان بالتمر - صغير",
    nameEn: "Pecan Date Cake Mousse - Small",
    price: 35,
    department: "cake" as ProductDept,
    category: "Mousse Cake",
    imageUri: "",
    isAvailable: true,
    sortOrder: 4030,
  },
  {
    id: "lavi-050",
    name: "موس كيك التيراميسو - صغير",
    nameEn: "Tiramisu Cake Mousse - Small",
    price: 35,
    department: "cake" as ProductDept,
    category: "Mousse Cake",
    imageUri: "",
    isAvailable: true,
    sortOrder: 4040,
  },
];

// ── Laviviane Bites ────────────────────────────────────────────────────────────

const LAVIVIANE_BITES: LavivianeProductSeed[] = [
  {
    id: "lavi-051",
    name: "بايتس البيكان بالتمر - صغير 9 حبات",
    nameEn: "Pecan Date Bites Small 9 Pcs",
    price: 48,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5010,
  },
  {
    id: "lavi-052",
    name: "بايتس البيكان بالتمر - كبير 24 حبة",
    nameEn: "Pecan Date Bites Large 24 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5020,
  },
  {
    id: "lavi-053",
    name: "صينية بايتس البيكان بالتمر - 49 حبة",
    nameEn: "Pecan Date Bites Tray 49 Pcs",
    price: 259,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5030,
  },
  {
    id: "lavi-054",
    name: "بايتس التيراميسو - صغير 9 حبات",
    nameEn: "Tiramisu Bites Small 9 Pcs",
    price: 48,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5040,
  },
  {
    id: "lavi-055",
    name: "بايتس التيراميسو - كبير 24 حبة",
    nameEn: "Tiramisu Bites Large 24 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5050,
  },
  {
    id: "lavi-056",
    name: "صينية بايتس التيراميسو - 49 حبة",
    nameEn: "Tiramisu Bites Tray 49 Pcs",
    price: 259,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5060,
  },
  {
    id: "lavi-057",
    name: "صينية بايتس مشكل - صغير 25 حبة",
    nameEn: "Mix Bites Tray Small 25 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5070,
  },
  {
    id: "lavi-058",
    name: "بايتس العقيلي - صغير 9 حبات",
    nameEn: "Oqaili Bites Small 9 Pcs",
    price: 48,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5080,
  },
  {
    id: "lavi-059",
    name: "بايتس العقيلي - كبير 24 حبة",
    nameEn: "Oqaili Bites Large 24 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5090,
  },
  {
    id: "lavi-060",
    name: "صينية بايتس العقيلي - 49 حبة",
    nameEn: "Oqaili Bites Tray 49 Pcs",
    price: 259,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5100,
  },
  {
    id: "lavi-061",
    name: "بايتس التشيز كريم برولية - صغير 9 حبات",
    nameEn: "Cream Brulee Cheese Bites Small 9 Pcs",
    price: 48,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5110,
  },
  {
    id: "lavi-062",
    name: "بايتس التشيز كريم برولية - كبير 27 حبة",
    nameEn: "Cream Brulee Cheese Bites Large 27 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5120,
  },
  {
    id: "lavi-063",
    name: "بايتس الليمون - صغير 9 حبات",
    nameEn: "Lemon Bites Small 9 Pcs",
    price: 48,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5130,
  },
  {
    id: "lavi-064",
    name: "بايتس الليمون - كبير 24 حبة",
    nameEn: "Lemon Bites Large 24 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5140,
  },
  {
    id: "lavi-065",
    name: "بايتس موس الشوكولاتة - صغير 9 حبات",
    nameEn: "Chocolate Mousse Bites Small 9 Pcs",
    price: 48,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5150,
  },
  {
    id: "lavi-066",
    name: "بايتس موس الشوكولاتة - كبير 24 حبة",
    nameEn: "Chocolate Mousse Bites Large 24 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5160,
  },
  {
    id: "lavi-067",
    name: "صينية بايتس موس الشوكولاتة - 49 حبة",
    nameEn: "Chocolate Mousse Bites Tray 49 Pcs",
    price: 259,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5170,
  },
  {
    id: "lavi-068",
    name: "بايتس نوتيلا فستق - صغير 9 حبات",
    nameEn: "Nutella Pistachio Bites Small 9 Pcs",
    price: 48,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5180,
  },
  {
    id: "lavi-069",
    name: "بايتس نوتيلا فستق - كبير 24 حبة",
    nameEn: "Nutella Pistachio Bites Large 24 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5190,
  },
  {
    id: "lavi-070",
    name: "بايتس الميل فوي - صغير 9 حبات",
    nameEn: "Mille Feuille Bites Small 9 Pcs",
    price: 48,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5200,
  },
  {
    id: "lavi-071",
    name: "بايتس الميل فوي - كبير 39 حبة",
    nameEn: "Mille Feuille Bites Large 39 Pcs",
    price: 145,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5210,
  },
  {
    id: "lavi-072",
    name: "صينية بايتس مشكل - 56 حبة",
    nameEn: "Mix Bites Tray 56 Pcs",
    price: 280,
    department: "cake" as ProductDept,
    category: "Laviviane Bites",
    imageUri: "",
    isAvailable: true,
    sortOrder: 5220,
  },
];

// ── Sandwich ───────────────────────────────────────────────────────────────────

const SANDWICH: LavivianeProductSeed[] = [
  {
    id: "lavi-073",
    name: "ساندويش بيبي لاففيان مشكل 28 حبة - صغير",
    nameEn: "Laviviane Baby Sandwich Mix 28 Pcs - Small",
    price: 92,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6010,
  },
  {
    id: "lavi-074",
    name: "ساندويش بيبي لاففيان مشكل 56 حبة - كبير",
    nameEn: "Laviviane Baby Sandwich Mix 56 Pcs - Large",
    price: 184,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6020,
  },
  {
    id: "lavi-075",
    name: "ساندويش مشكل لاففيان 10 حبة - صغير",
    nameEn: "Laviviane Mix Sandwich 10 Pcs - Small",
    price: 58,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6030,
  },
  {
    id: "lavi-076",
    name: "ساندويش مشكل لاففيان 20 حبة - كبير",
    nameEn: "Laviviane Mix Sandwich 20 Pcs - Large",
    price: 115,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6040,
  },
  {
    id: "lavi-077",
    name: "ساندويش مشكل لاففيان - كبير",
    nameEn: "Laviviane Mixed Sandwiches - Large",
    price: 120,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6050,
  },
  {
    id: "lavi-078",
    name: "بوكس مسخن دجاج 21 حبة",
    nameEn: "Muskhan Chicken Box 21 Pcs",
    price: 138,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6060,
  },
  {
    id: "lavi-079",
    name: "بوكس مسخن دجاج 26 حبة",
    nameEn: "Muskhan Chicken Box 26 Pcs",
    price: 180,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6070,
  },
  {
    id: "lavi-080",
    name: "سليزون نصف كيلو",
    nameEn: "Salizon 1/2 kg",
    price: 92,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6080,
  },
  {
    id: "lavi-081",
    name: "سليزون كيلو",
    nameEn: "Salizon 1 kg",
    price: 184,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6090,
  },
  {
    id: "lavi-082",
    name: "كراكرز سليزون",
    nameEn: "Salizon Crackers",
    price: 94,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6100,
  },
  {
    id: "lavi-083",
    name: "بوكس كرات الجبن",
    nameEn: "Cheese Ball Box",
    price: 145,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6110,
  },
  {
    id: "lavi-084",
    name: "تشكيلة مالحة لاففيان 3 أنواع",
    nameEn: "Laviviane Salty Assortment 3 Types",
    price: 150,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6120,
  },
  {
    id: "lavi-085",
    name: "صينية مالحة #3",
    nameEn: "Salty Tray #3",
    price: 437,
    department: "mawali" as ProductDept,
    category: "Sandwich",
    imageUri: "",
    isAvailable: true,
    sortOrder: 6130,
  },
];

// ── Luxury Chocolate ───────────────────────────────────────────────────────────

const LUXURY_CHOCOLATE: LavivianeProductSeed[] = [
  {
    id: "lavi-086",
    name: "بوكس شوكولاتة فاخر - بغلز كرانشي",
    nameEn: "Laviviane Luxury Chocolate Box - Crunchy Bugles",
    price: 165,
    department: "chocolate" as ProductDept,
    category: "Luxury Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 7010,
  },
  {
    id: "lavi-087",
    name: "بوكس شوكولاتة فاخر - كراميل كرانشي",
    nameEn: "Laviviane Luxury Chocolate Box - Crunchy Caramel",
    price: 165,
    department: "chocolate" as ProductDept,
    category: "Luxury Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 7020,
  },
  {
    id: "lavi-088",
    name: "بوكس شوكولاتة فاخر - فستق كرانشي",
    nameEn: "Laviviane Luxury Chocolate Box - Crunchy Pistachio",
    price: 165,
    department: "chocolate" as ProductDept,
    category: "Luxury Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 7030,
  },
  {
    id: "lavi-089",
    name: "بغلز مغطاة بالشوكولاتة - صغير",
    nameEn: "Bugles Covered with Chocolate - Small",
    price: 77,
    department: "chocolate" as ProductDept,
    category: "Luxury Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 7040,
  },
  {
    id: "lavi-090",
    name: "برتسلز مغطاة بالشوكولاتة - صغير",
    nameEn: "Pretzel Covered with Chocolate - Small",
    price: 107,
    department: "chocolate" as ProductDept,
    category: "Luxury Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 7050,
  },
  {
    id: "lavi-091",
    name: "بارات شوكولاتة مشكلة - صغير",
    nameEn: "Mixed Chocolate Bars - Small",
    price: 83,
    department: "chocolate" as ProductDept,
    category: "Luxury Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 7060,
  },
  {
    id: "lavi-092",
    name: "شوكولاتة فيوتين نوتيلا - صغير",
    nameEn: "Chocolate Feuilletine Nutella - Small",
    price: 115,
    department: "chocolate" as ProductDept,
    category: "Luxury Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 7070,
  },
  {
    id: "lavi-093",
    name: "بغلز مغطاة بالشوكولاتة - وسط",
    nameEn: "Bugles Covered with Chocolate - Medium",
    price: 110,
    department: "chocolate" as ProductDept,
    category: "Luxury Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 7080,
  },
  {
    id: "lavi-094",
    name: "برتسلز مغطاة بالشوكولاتة - وسط",
    nameEn: "Pretzels Covered with Chocolate - Medium",
    price: 115,
    department: "chocolate" as ProductDept,
    category: "Luxury Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 7090,
  },
  {
    id: "lavi-095",
    name: "بوكس شوكولاتة مشكلة 3 أنواع - وسط",
    nameEn: "Mixed Chocolate Box 3 Types - Medium",
    price: 280,
    department: "chocolate" as ProductDept,
    category: "Luxury Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 7100,
  },
];

// ── Occasion Chocolate ─────────────────────────────────────────────────────────

const OCCASION_CHOCOLATE: LavivianeProductSeed[] = [
  {
    id: "lavi-096",
    name: "تشكيلة شوكولاتة للمناسبات #1",
    nameEn: "Assortment of Chocolate for Occasions #1",
    price: 550,
    department: "chocolate" as ProductDept,
    category: "Occasion Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 8010,
  },
  {
    id: "lavi-097",
    name: "تشكيلة شوكولاتة للمناسبات #2",
    nameEn: "Assortment of Chocolate for Occasions #2",
    price: 630,
    department: "chocolate" as ProductDept,
    category: "Occasion Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 8020,
  },
  {
    id: "lavi-098",
    name: "تشكيلة شوكولاتة للمناسبات #3",
    nameEn: "Assortment of Chocolate for Occasions #3",
    price: 550,
    department: "chocolate" as ProductDept,
    category: "Occasion Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 8030,
  },
  {
    id: "lavi-099",
    name: "تشكيلة شوكولاتة للمناسبات #4",
    nameEn: "Assortment of Chocolate for Occasions #4",
    price: 550,
    department: "chocolate" as ProductDept,
    category: "Occasion Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 8040,
  },
  {
    id: "lavi-100",
    name: "تشكيلة شوكولاتة للمناسبات #5",
    nameEn: "Assortment of Chocolate for Occasions #5",
    price: 620,
    department: "chocolate" as ProductDept,
    category: "Occasion Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 8050,
  },
  {
    id: "lavi-101",
    name: "صينية شوكولاتة دائرية بالورد",
    nameEn: "Chocolate Round Rose Tray",
    price: 590,
    department: "chocolate" as ProductDept,
    category: "Occasion Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 8060,
  },
  {
    id: "lavi-102",
    name: "صينية دائرية بقاعدة خشبية بنفسجية",
    nameEn: "Round Tray with Purple Wooden Base",
    price: 796,
    department: "chocolate" as ProductDept,
    category: "Occasion Chocolate",
    imageUri: "",
    isAvailable: true,
    sortOrder: 8070,
  },
];

// ── Distributions and Gifts ────────────────────────────────────────────────────

const DISTRIBUTIONS_AND_GIFTS: LavivianeProductSeed[] = [
  {
    id: "lavi-103",
    name: "ظروف هدايا لاففيان - 35 ظرف",
    nameEn: "Laviviane Gift Envelopes 35 Pcs",
    price: 320,
    department: "chocolate" as ProductDept,
    category: "Distributions and Gifts",
    imageUri: "",
    isAvailable: true,
    sortOrder: 9010,
  },
];

const RAW_LAVIVIANE_PRODUCTS: LavivianeProductSeed[] = [
  ...PAGE2,
  ...PAGE3,
  ...PAGE4,
  ...LAVIVIANE_CAKES_EXTRA,
  ...CELEBRATION_BITES,
  ...MOUSSE_CAKE,
  ...LAVIVIANE_BITES,
  ...SANDWICH,
  ...LUXURY_CHOCOLATE,
  ...OCCASION_CHOCOLATE,
  ...DISTRIBUTIONS_AND_GIFTS,
];

export const LAVIVIANE_PRODUCTS: LavivianeProductSeed[] = RAW_LAVIVIANE_PRODUCTS.reduce<LavivianeProductSeed[]>((acc, product) => {
  const key = normalizeProductKey(product);
  const exists = acc.some((item) => normalizeProductKey(item) === key);
  if (!exists) acc.push(product);
  return acc;
}, []).sort((a, b) => a.sortOrder - b.sortOrder);

export const LAVIVIANE_CATALOG_SUMMARY = {
  companyId: LAVIVIANE_COMPANY_ID,
  source: "Laviviane product cards (pages 2–4 + full PDF catalog)",
  productCount: LAVIVIANE_PRODUCTS.length,
  categoryOrder: LAVIVIANE_CATEGORY_ORDER,
  duplicatePolicy: "Products are considered duplicates only when normalized category, name, and price are identical. Different sizes/counts remain separate products.",
} as const;

export function buildLavivianeProducts(now = new Date().toISOString()): Product[] {
  return LAVIVIANE_PRODUCTS.map((product) => ({
    ...product,
    companyId: LAVIVIANE_COMPANY_ID,
    createdAt: now,
    updatedAt: now,
  }));
}
